// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yirewozehmgljvuxffzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcmV3b3plaG1nbGp2dXhmZnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODM1MTMsImV4cCI6MjA2Mjk1OTUxM30.QXxU8UXvPCB_ay57VoY_8WINaoNtKuUhQP0_IjQKECc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);